<?php
$bio = 'Bio : Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet interdum risus, tempus fermentum turpis. Suspendisse potenti. Fusce vestibulum feugiat dui, in condimentum sapien eleifend sed. Nunc aliquam odio ac porttitor gravida. Curabitur id neque ac nibh tempor vulputate. Donec egestas arcu nec semper convallis.';

$peoples = [
    ['id' =>1, 'name' => 'Jean Castex', 'age' => 31, 'picture' => 'https://images.lanouvellerepublique.fr/image/upload/t_1020w/5d1229021f1a90fe7f8b4580.jpg', 'bio' => 'Il a un accent chantant, sa maladresse touchante en fera le compagnon idéal de vos soirées. Un conseil : ne le laissez pas parler des vaccins!', 'specialities' => ['Bon cuisinier','Capitaine','Présentation soignée',]],
    ['id' =>2, 'name' => 'Teddy Riner', 'age' => 29, 'picture' => 'https://images.lanouvellerepublique.fr/image/upload/t_1020w/5d1229021f1a90fe7f8b4580.jpg', 'bio' => 'Vous aimez la testostérone, Teddy est l\'homme le plus fort de la caserne. Rassurez-vous il n\'utilisera pas ses prises de judo hors du tatami. ', 'specialities' => ['Maitre des arts martiaux','Junior','Tolérance approfondie',]],
    ['id' =>3, 'name' => 'Mikel Arteta', 'age' => 36, 'picture' => 'https://images.lanouvellerepublique.fr/image/upload/t_1020w/5d1229021f1a90fe7f8b4580.jpg', 'bio' => 'Joueur de football inconnu, il s\'est reconverti mais reste toujours inconnu. Alors découvrez-le.', 'specialities' => ['Agilité acrue','Monté de corde top niveau','Egaux surdimensionné',]],
    ['id' =>4, 'name' => 'Mike Horn', 'age' => 45, 'picture' => 'https://images.lanouvellerepublique.fr/image/upload/t_1020w/5d1229021f1a90fe7f8b4580.jpg', 'bio' => 'Cet aventurier pourra vous raconter ses voyages et vous aider à vous évader de cette sinistre période. Mais attention, accent incompréhensible.', 'specialities' => ['Sens du devoir','Adaptation en milieu hostile développée','Généreux',]],
    ['id' =>5, 'name' => 'Jim Carrey', 'age' => 52, 'picture' => 'https://images.lanouvellerepublique.fr/image/upload/t_1020w/5d1229021f1a90fe7f8b4580.jpg', 'bio' => 'lol', 'specialities' => ['Autodérision','Serviable','Jeux de rôle',]],
];